- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/logo.svg'
- name: INSTALLATION_NAME
  value: 'Chatwoot'
- name: BRAND_URL
  value: 'https://www.chatwoot.com'
- name: WIDGET_BRAND_URL
  value: 'https://www.chatwoot.com'
- name: TERMS_URL
  value: 'https://www.chatwoot.com/terms-of-service'
- name: PRIVACY_URL
  value: 'https://www.chatwoot.com/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
- name: MAILER_INBOUND_EMAIL_DOMAIN
  value:
- name: MAILER_SUPPORT_EMAIL
  value:
- name: CREATE_NEW_ACCOUNT_FROM_DASHBOARD
  value: false
- name: BRAND_NAME
  value: 'Chatwoot'
- name: 'INSTALLATION_EVENTS_WEBHOOK_URL'
  value: 
